---
homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
    sensor.dark_sky_*:
      homebridge_hidden: true
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

system_health:
config:
cloud:
mobile_app:
frontend:
  javascript_version: latest
discovery:
updater:
  include_used_components: true
sun:
zeroconf:
ifttt:
  key: !secret ifttt_key

# Config files
history: !include config/configs/history.yaml
hue: !include config/configs/hue.yaml
logbook: !include config/configs/logbook.yaml
logger: !include config/configs/logger.yaml
recorder: !include config/configs/recorder.yaml
tts: !include config/configs/tts.yaml
weather: !include config/configs/weather.yaml
zwave: !include config/configs/zwave.yaml

group: !include_dir_merge_named config/group
device_tracker: !include_dir_merge_list config/device_tracker
sensor: !include_dir_merge_list config/sensor
automation: !include_dir_merge_list config/automation
scene: !include_dir_merge_list config/scene
switch: !include_dir_merge_list config/switch
script: !include_dir_merge_named config/script
input_boolean: !include_dir_merge_named config/input_boolean
shell_command: !include_dir_merge_named config/shell_command
