homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassisant_longitude
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
    sensor.dark_sky_*:
      homebridge_hidden: true
  packages: !include_dir_named packages
