---

notify_engine:
  sequence:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.text_notifications
          state: 'on'

    - service_template: >
          {% if who == 'randy' %}
            notify.ios_miphonex
          {% elif who == 'lyndsey' %}
            notify.ios_lyndseys_iphone
          {% elif who == 'family' %}
            notify.ios_family
          {% else %}
            notify.ios_family
          {% endif %}
      data_template:
        title: "{{ title }}"
        message: "{{ value1 }} {{ value2 }} {{ value3 }}"
        data:
          attachment:
            url: "{{ url }}"
            content-type: "{{ content_type }}"
            hide-thumbnail: false
          push:
            sound: "{{ ios_sound }}"
            badge: "{{ ios_badge }}"
            category: "{{ ios_category }}"
            entity_id: "{{ camera_entity }}"
